### PR TITLE
set engines and adjust ci + documentation

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
Closes #34 #35

### CODE REVIEW

**Comment by Ethan-Arrowood** [comment]
@cadienvan would you like to review this and co-author the commit with me? Your work in #34 and #35 is good and I want to give credit where credit is deserved 😄

**Review by Cadienvan — APPROVED** [review]
It seems perfect to me! Brilliant, I didn't think about the experimental flag!

**Comment by Cadienvan** [comment]
Thank you for your kindness! Sure! I reviewed it, dunno how to co-author it :D Is it enough for you to bring a co-authored-by in the commit message when merging?

**Comment by Ethan-Arrowood** [comment]
I will amend the commit so its included in the merge :)

**Comment by Cadienvan** [comment]
Thanks! So can I delete my branches now?

**Pull request merged**
